spring:
  datasource:
    url: jdbc:h2:mem:ds-pessoa
    name: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      
  cloud:
    service-registry:
      auto-registration:
        enabled: false      