server:
  port: ${PORT:0}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}  
  
spring:
  profiles:
    active: test
  application:
    name: ds-conta-corrente
  rabbitmq:
    addresses: ${RABBITMQ_SERVER:localhost:5672}
    username: ds-banco
    password: ABC_BANCO
    virtualhost: /
    
  cloud:
    function:
      definition: subscribeContaCorrenteCreated;publishContaCorrenteProcessed;publishProdutosContaCorrenteCreated;publishContaCorrenteCreated
    stream:
      binders:
        rabbitMQ:
          type: rabbit

      bindings:
        springcloudbusinput:
          destination: springCloudBus
          group: q-cloudbus-ds-conta-corrente
                
        subscribeContaCorrenteCreated-in-0:
          destination: x-conta-corrente-created
          group: q-conta-corrente-created
          consumer:
            maxAttempts: 1

        publishContaCorrenteCreated-out-0:
          destination: x-conta-corrente-processed

        publishContaCorrenteProcessed-out-0:
          destination: x-conta-corrente-processed
          
        publishProdutosContaCorrenteCreated-out-0:
          destination: x-produtos-conta-corrente-created

      rabbit:
        bindings:
          subscribeContaCorrenteCreated-in-0:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              requeueRejected: false

          publishContaCorrenteCreated-out-0:
            producer:
              exchangeType: fanout

          publishContaCorrenteProcessed-out-0:
            producer:
              exchangeType: fanout
              
          publishProdutosContaCorrenteCreated-out-0:
            producer:
              exchangeType: fanout

  jpa:
    open-in-view: false
    
banco:
  agencia:
    numero: ${AGENCIA_NUMERO:3271}
    
resilience4j.circuitbreaker:
  instances:
    findProductAccount:
      slidingWindowSize: 8   
      minimumNumberOfCalls: 4
