server:
  port: ${PORT:0}
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: ds-conta-corrente-produtos
  profiles:
    active: test
  rabbitmq:
    addresses: localhost:5672
    username: ds-banco
    password: ABC_BANCO
    virtualhost: /
    
  cloud:
    function:
      definition: subscribeProdutosContaCorrenteCreated;publishProdutosContaCorrenteProcessed;publishContaCorrenteCreated

    stream:
      binders:
        rabbitMQ:
          type: rabbit

      bindings:
        springcloudbusinput:
          destination: springCloudBus
          group: q-cloudbus-ds-conta-corrente
                
        subscribeProdutosContaCorrenteCreated-in-0:
          destination: x-produtos-conta-corrente-created
          group: q-produtos-conta-corrente-created
          consumer:
            maxAttempts: 1

        publishContaCorrenteCreated-out-0:
          destination: x-conta-corrente-created

        publishProdutosContaCorrenteProcessed-out-0:
          destination: x-produtos-conta-corrente-processed

      rabbit:
        bindings:
          subscribeProdutosContaCorrenteCreated-in-0:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              requeueRejected: false

          publishContaCorrenteCreated-out-0:
            producer:
              exchangeType: fanout

          publishProdutosContaCorrenteProcessed-out-0:
            producer:
              exchangeType: fanout

  jpa:
    open-in-view: false